//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.14 at 03:39:28 PM CET 
//


package pl.edu.wit.jpa.dao.companyB.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.edu.wit.jpa.dao.companyB.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CustomerSync_QNAME = new QName("firmaB", "customerSync");
    private final static QName _OrderSync_QNAME = new QName("firmaB", "orderSync");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.edu.wit.jpa.dao.companyB.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CbCustomerSync }
     * 
     */
    public CbCustomerSync createCbCustomerSync() {
        return new CbCustomerSync();
    }

    /**
     * Create an instance of {@link pl.edu.wit.jpa.dao.companyB.model.CbOrderList }
     * 
     */
    public pl.edu.wit.jpa.dao.companyB.model.CbOrderList createCbOrderList() {
        return new pl.edu.wit.jpa.dao.companyB.model.CbOrderList();
    }

    /**
     * Create an instance of {@link pl.edu.wit.jpa.dao.companyB.model.CbContactData }
     * 
     */
    public pl.edu.wit.jpa.dao.companyB.model.CbContactData createCbContactData() {
        return new CbContactData();
    }

    /**
     * Create an instance of {@link pl.edu.wit.jpa.dao.companyB.model.CbAddress }
     * 
     */
    public pl.edu.wit.jpa.dao.companyB.model.CbAddress createCbAddress() {
        return new CbAddress();
    }

    /**
     * Create an instance of {@link pl.edu.wit.jpa.dao.companyB.model.CbDocument }
     * 
     */
    public pl.edu.wit.jpa.dao.companyB.model.CbDocument createCbDocument() {
        return new CbDocument();
    }

    /**
     * Create an instance of {@link pl.edu.wit.jpa.dao.companyB.model.CbCompanyData }
     * 
     */
    public pl.edu.wit.jpa.dao.companyB.model.CbCompanyData createCbCompanyData() {
        return new CbCompanyData();
    }

    /**
     * Create an instance of {@link pl.edu.wit.jpa.dao.companyB.model.CbPersonData }
     * 
     */
    public pl.edu.wit.jpa.dao.companyB.model.CbPersonData createCbPersonData() {
        return new CbPersonData();
    }

    /**
     * Create an instance of {@link pl.edu.wit.jpa.dao.companyB.model.CbCustomers }
     * 
     */
    public pl.edu.wit.jpa.dao.companyB.model.CbCustomers createCbCustomers() {
        return new CbCustomers();
    }

    /**
     * Create an instance of {@link CbOrderCustomer }
     * 
     */
    public CbOrderCustomer createCbOrderCustomer() {
        return new CbOrderCustomer();
    }

    /**
     * Create an instance of {@link pl.edu.wit.jpa.dao.companyB.model.CbAccount }
     * 
     */
    public pl.edu.wit.jpa.dao.companyB.model.CbAccount createCbAccount() {
        return new CbAccount();
    }

    /**
     * Create an instance of {@link pl.edu.wit.jpa.dao.companyB.model.CbCustomer }
     * 
     */
    public pl.edu.wit.jpa.dao.companyB.model.CbCustomer createCbCustomer() {
        return new CbCustomer();
    }

    /**
     * Create an instance of {@link pl.edu.wit.jpa.dao.companyB.model.CbOrder }
     * 
     */
    public pl.edu.wit.jpa.dao.companyB.model.CbOrder createCbOrder() {
        return new CbOrder();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CbCustomerSync }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "firmaB", name = "customerSync")
    public JAXBElement<CbCustomerSync> createCustomerSync(CbCustomerSync value) {
        return new JAXBElement<CbCustomerSync>(_CustomerSync_QNAME, CbCustomerSync.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link pl.edu.wit.jpa.dao.companyB.model.CbOrderList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "firmaB", name = "orderSync")
    public JAXBElement<pl.edu.wit.jpa.dao.companyB.model.CbOrderList> createOrderSync(pl.edu.wit.jpa.dao.companyB.model.CbOrderList value) {
        return new JAXBElement<pl.edu.wit.jpa.dao.companyB.model.CbOrderList>(_OrderSync_QNAME, CbOrderList.class, null, value);
    }

}
