//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.08 at 12:32:02 AM CET 
//


package pl.edu.wit.jpa.dao.companyB.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.edu.wit.jpa.dao.companyB.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CustomerSync_QNAME = new QName("firmaB", "customerSync");
    private final static QName _OrderSync_QNAME = new QName("firmaB", "orderSync");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.edu.wit.jpa.dao.companyB.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CbCustomerSync }
     * 
     */
    public CbCustomerSync createCbCustomerSync() {
        return new CbCustomerSync();
    }

    /**
     * Create an instance of {@link CbOrderList }
     * 
     */
    public CbOrderList createCbOrderList() {
        return new CbOrderList();
    }

    /**
     * Create an instance of {@link CbContactData }
     * 
     */
    public CbContactData createCbContactData() {
        return new CbContactData();
    }

    /**
     * Create an instance of {@link CbAddress }
     * 
     */
    public CbAddress createCbAddress() {
        return new CbAddress();
    }

    /**
     * Create an instance of {@link CbDocument }
     * 
     */
    public CbDocument createCbDocument() {
        return new CbDocument();
    }

    /**
     * Create an instance of {@link CbCompanyData }
     * 
     */
    public CbCompanyData createCbCompanyData() {
        return new CbCompanyData();
    }

    /**
     * Create an instance of {@link CbPersonData }
     * 
     */
    public CbPersonData createCbPersonData() {
        return new CbPersonData();
    }

    /**
     * Create an instance of {@link CbCustomers }
     * 
     */
    public CbCustomers createCbCustomers() {
        return new CbCustomers();
    }

    /**
     * Create an instance of {@link CbOrderCustomer }
     * 
     */
    public CbOrderCustomer createCbOrderCustomer() {
        return new CbOrderCustomer();
    }

    /**
     * Create an instance of {@link CbAccount }
     * 
     */
    public CbAccount createCbAccount() {
        return new CbAccount();
    }

    /**
     * Create an instance of {@link CbCustomer }
     * 
     */
    public CbCustomer createCbCustomer() {
        return new CbCustomer();
    }

    /**
     * Create an instance of {@link CbOrder }
     * 
     */
    public CbOrder createCbOrder() {
        return new CbOrder();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CbCustomerSync }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "firmaB", name = "customerSync")
    public JAXBElement<CbCustomerSync> createCustomerSync(CbCustomerSync value) {
        return new JAXBElement<CbCustomerSync>(_CustomerSync_QNAME, CbCustomerSync.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CbOrderList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "firmaB", name = "orderSync")
    public JAXBElement<CbOrderList> createOrderSync(CbOrderList value) {
        return new JAXBElement<CbOrderList>(_OrderSync_QNAME, CbOrderList.class, null, value);
    }

}
