//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.14 at 03:39:28 PM CET 
//


package pl.edu.wit.jpa.dao.companyA.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.edu.wit.jpa.dao.companyA.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CustomerDatas_QNAME = new QName("", "customerDatas");
    private final static QName _Orders_QNAME = new QName("", "orders");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.edu.wit.jpa.dao.companyA.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link pl.edu.wit.jpa.dao.companyA.model.CaOrders }
     * 
     */
    public pl.edu.wit.jpa.dao.companyA.model.CaOrders createCaOrders() {
        return new pl.edu.wit.jpa.dao.companyA.model.CaOrders();
    }

    /**
     * Create an instance of {@link CaCustomerDataList }
     * 
     */
    public CaCustomerDataList createCaCustomerDataList() {
        return new CaCustomerDataList();
    }

    /**
     * Create an instance of {@link pl.edu.wit.jpa.dao.companyA.model.CaAddress }
     * 
     */
    public pl.edu.wit.jpa.dao.companyA.model.CaAddress createCaAddress() {
        return new CaAddress();
    }

    /**
     * Create an instance of {@link CaCustomerData }
     * 
     */
    public CaCustomerData createCaCustomerData() {
        return new CaCustomerData();
    }

    /**
     * Create an instance of {@link CaOrderCustomerData }
     * 
     */
    public CaOrderCustomerData createCaOrderCustomerData() {
        return new CaOrderCustomerData();
    }

    /**
     * Create an instance of {@link pl.edu.wit.jpa.dao.companyA.model.CaAccount }
     * 
     */
    public pl.edu.wit.jpa.dao.companyA.model.CaAccount createCaAccount() {
        return new CaAccount();
    }

    /**
     * Create an instance of {@link pl.edu.wit.jpa.dao.companyA.model.CaOrder }
     * 
     */
    public pl.edu.wit.jpa.dao.companyA.model.CaOrder createCaOrder() {
        return new CaOrder();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CaCustomerDataList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "customerDatas")
    public JAXBElement<CaCustomerDataList> createCustomerDatas(CaCustomerDataList value) {
        return new JAXBElement<CaCustomerDataList>(_CustomerDatas_QNAME, CaCustomerDataList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link pl.edu.wit.jpa.dao.companyA.model.CaOrders }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "orders")
    public JAXBElement<pl.edu.wit.jpa.dao.companyA.model.CaOrders> createOrders(pl.edu.wit.jpa.dao.companyA.model.CaOrders value) {
        return new JAXBElement<pl.edu.wit.jpa.dao.companyA.model.CaOrders>(_Orders_QNAME, CaOrders.class, null, value);
    }

}
