//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.14 at 03:39:28 PM CET 
//


package pl.edu.wit.jpa.dao.companyA.model;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.CollectionTable;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OrderColumn;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for orderCustomerData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderCustomerData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="surname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pesel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="documentCountry" type="{firmaA}countryCode" minOccurs="0"/>
 *         &lt;element name="documentType" type="{firmaA}documentType" minOccurs="0"/>
 *         &lt;element name="documentNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nip" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="phone" type="{firmaA}phone" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="email" type="{firmaA}email" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="address" type="{firmaA}address" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="account" type="{firmaA}account" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{firmaA}customerDataType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderCustomerData", propOrder = {
    "id",
    "name",
    "surname",
    "pesel",
    "documentCountry",
    "documentType",
    "documentNumber",
    "companyName",
    "nip",
    "phone",
    "email",
    "address",
    "account"
})
@Entity(name = "CaOrderCustomerData")
@Table(name = "CAORDERCUSTOMERDATA")
@Inheritance(strategy = InheritanceType.JOINED)
public class CaOrderCustomerData
    implements Serializable, Equals, HashCode
{

    protected Long id;
    protected String name;
    protected String surname;
    protected String pesel;
    protected CaCountryCode documentCountry;
    protected CaDocumentType documentType;
    protected String documentNumber;
    protected String companyName;
    protected BigInteger nip;
    protected List<String> phone;
    protected List<String> email;
    protected List<CaAddress> address;
    protected List<CaAccount> account;
    @XmlAttribute(name = "type")
    protected CaCustomerDataType type;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "id", scale = 0)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "NAME_", length = 255)
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the surname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "SURNAME", length = 255)
    public String getSurname() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurname(String value) {
        this.surname = value;
    }

    /**
     * Gets the value of the pesel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PESEL", length = 255)
    public String getPesel() {
        return pesel;
    }

    /**
     * Sets the value of the pesel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPesel(String value) {
        this.pesel = value;
    }

    /**
     * Gets the value of the documentCountry property.
     * 
     * @return
     *     possible object is
     *     {@link CaCountryCode }
     *     
     */
    @Basic
    @Column(name = "DOCUMENTCOUNTRY", length = 255)
    @Enumerated(EnumType.STRING)
    public CaCountryCode getDocumentCountry() {
        return documentCountry;
    }

    /**
     * Sets the value of the documentCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaCountryCode }
     *     
     */
    public void setDocumentCountry(CaCountryCode value) {
        this.documentCountry = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link CaDocumentType }
     *     
     */
    @Basic
    @Column(name = "DOCUMENTTYPE", length = 255)
    @Enumerated(EnumType.STRING)
    public CaDocumentType getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaDocumentType }
     *     
     */
    public void setDocumentType(CaDocumentType value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the documentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "DOCUMENTNUMBER", length = 255)
    public String getDocumentNumber() {
        return documentNumber;
    }

    /**
     * Sets the value of the documentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentNumber(String value) {
        this.documentNumber = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "COMPANYNAME", length = 255)
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the nip property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "NIP", precision = 20, scale = 0)
    public BigInteger getNip() {
        return nip;
    }

    /**
     * Sets the value of the nip property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNip(BigInteger value) {
        this.nip = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhone().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    @ElementCollection
    @OrderColumn(name = "HJINDEX")
    @Column(name = "HJVALUE", length = 255)
    @CollectionTable(name = "CAORDERCUSTOMERDATA_PHONE", joinColumns = {
        @JoinColumn(name = "ID")
    })
    public List<String> getPhone() {
        if (phone == null) {
            phone = new ArrayList<String>();
        }
        return this.phone;
    }

    /**
     * 
     * 
     */
    public void setPhone(List<String> phone) {
        this.phone = phone;
    }

    /**
     * Gets the value of the email property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the email property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    @ElementCollection
    @OrderColumn(name = "HJINDEX")
    @Column(name = "HJVALUE", length = 255)
    @CollectionTable(name = "CAORDERCUSTOMERDATA_EMAIL", joinColumns = {
        @JoinColumn(name = "ID")
    })
    public List<String> getEmail() {
        if (email == null) {
            email = new ArrayList<String>();
        }
        return this.email;
    }

    /**
     * 
     * 
     */
    public void setEmail(List<String> email) {
        this.email = email;
    }

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CaAddress }
     * 
     * 
     */
    @OneToMany(targetEntity = CaAddress.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ADDRESS_CAORDERCUSTOMERDATA__0")
    public List<CaAddress> getAddress() {
        if (address == null) {
            address = new ArrayList<CaAddress>();
        }
        return this.address;
    }

    /**
     * 
     * 
     */
    public void setAddress(List<CaAddress> address) {
        this.address = address;
    }

    /**
     * Gets the value of the account property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the account property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CaAccount }
     * 
     * 
     */
    @OneToMany(targetEntity = CaAccount.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ACCOUNT_CAORDERCUSTOMERDATA__0")
    public List<CaAccount> getAccount() {
        if (account == null) {
            account = new ArrayList<CaAccount>();
        }
        return this.account;
    }

    /**
     * 
     * 
     */
    public void setAccount(List<CaAccount> account) {
        this.account = account;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CaCustomerDataType }
     *     
     */
    @Basic
    @Column(name = "TYPE_", length = 255)
    @Enumerated(EnumType.STRING)
    public CaCustomerDataType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaCustomerDataType }
     *     
     */
    public void setType(CaCustomerDataType value) {
        this.type = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof CaOrderCustomerData)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final CaOrderCustomerData that = ((CaOrderCustomerData) object);
        {
            Long lhsId;
            lhsId = this.getId();
            Long rhsId;
            rhsId = that.getId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "id", lhsId), LocatorUtils.property(thatLocator, "id", rhsId), lhsId, rhsId)) {
                return false;
            }
        }
        {
            String lhsName;
            lhsName = this.getName();
            String rhsName;
            rhsName = that.getName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "name", lhsName), LocatorUtils.property(thatLocator, "name", rhsName), lhsName, rhsName)) {
                return false;
            }
        }
        {
            String lhsSurname;
            lhsSurname = this.getSurname();
            String rhsSurname;
            rhsSurname = that.getSurname();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "surname", lhsSurname), LocatorUtils.property(thatLocator, "surname", rhsSurname), lhsSurname, rhsSurname)) {
                return false;
            }
        }
        {
            String lhsPesel;
            lhsPesel = this.getPesel();
            String rhsPesel;
            rhsPesel = that.getPesel();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "pesel", lhsPesel), LocatorUtils.property(thatLocator, "pesel", rhsPesel), lhsPesel, rhsPesel)) {
                return false;
            }
        }
        {
            CaCountryCode lhsDocumentCountry;
            lhsDocumentCountry = this.getDocumentCountry();
            CaCountryCode rhsDocumentCountry;
            rhsDocumentCountry = that.getDocumentCountry();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "documentCountry", lhsDocumentCountry), LocatorUtils.property(thatLocator, "documentCountry", rhsDocumentCountry), lhsDocumentCountry, rhsDocumentCountry)) {
                return false;
            }
        }
        {
            CaDocumentType lhsDocumentType;
            lhsDocumentType = this.getDocumentType();
            CaDocumentType rhsDocumentType;
            rhsDocumentType = that.getDocumentType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "documentType", lhsDocumentType), LocatorUtils.property(thatLocator, "documentType", rhsDocumentType), lhsDocumentType, rhsDocumentType)) {
                return false;
            }
        }
        {
            String lhsDocumentNumber;
            lhsDocumentNumber = this.getDocumentNumber();
            String rhsDocumentNumber;
            rhsDocumentNumber = that.getDocumentNumber();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "documentNumber", lhsDocumentNumber), LocatorUtils.property(thatLocator, "documentNumber", rhsDocumentNumber), lhsDocumentNumber, rhsDocumentNumber)) {
                return false;
            }
        }
        {
            String lhsCompanyName;
            lhsCompanyName = this.getCompanyName();
            String rhsCompanyName;
            rhsCompanyName = that.getCompanyName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "companyName", lhsCompanyName), LocatorUtils.property(thatLocator, "companyName", rhsCompanyName), lhsCompanyName, rhsCompanyName)) {
                return false;
            }
        }
        {
            BigInteger lhsNip;
            lhsNip = this.getNip();
            BigInteger rhsNip;
            rhsNip = that.getNip();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nip", lhsNip), LocatorUtils.property(thatLocator, "nip", rhsNip), lhsNip, rhsNip)) {
                return false;
            }
        }
        {
            List<String> lhsPhone;
            lhsPhone = (((this.phone!= null)&&(!this.phone.isEmpty()))?this.getPhone():null);
            List<String> rhsPhone;
            rhsPhone = (((that.phone!= null)&&(!that.phone.isEmpty()))?that.getPhone():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "phone", lhsPhone), LocatorUtils.property(thatLocator, "phone", rhsPhone), lhsPhone, rhsPhone)) {
                return false;
            }
        }
        {
            List<String> lhsEmail;
            lhsEmail = (((this.email!= null)&&(!this.email.isEmpty()))?this.getEmail():null);
            List<String> rhsEmail;
            rhsEmail = (((that.email!= null)&&(!that.email.isEmpty()))?that.getEmail():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "email", lhsEmail), LocatorUtils.property(thatLocator, "email", rhsEmail), lhsEmail, rhsEmail)) {
                return false;
            }
        }
        {
            List<CaAddress> lhsAddress;
            lhsAddress = (((this.address!= null)&&(!this.address.isEmpty()))?this.getAddress():null);
            List<CaAddress> rhsAddress;
            rhsAddress = (((that.address!= null)&&(!that.address.isEmpty()))?that.getAddress():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "address", lhsAddress), LocatorUtils.property(thatLocator, "address", rhsAddress), lhsAddress, rhsAddress)) {
                return false;
            }
        }
        {
            List<CaAccount> lhsAccount;
            lhsAccount = (((this.account!= null)&&(!this.account.isEmpty()))?this.getAccount():null);
            List<CaAccount> rhsAccount;
            rhsAccount = (((that.account!= null)&&(!that.account.isEmpty()))?that.getAccount():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "account", lhsAccount), LocatorUtils.property(thatLocator, "account", rhsAccount), lhsAccount, rhsAccount)) {
                return false;
            }
        }
        {
            CaCustomerDataType lhsType;
            lhsType = this.getType();
            CaCustomerDataType rhsType;
            rhsType = that.getType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "type", lhsType), LocatorUtils.property(thatLocator, "type", rhsType), lhsType, rhsType)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            Long theId;
            theId = this.getId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "id", theId), currentHashCode, theId);
        }
        {
            String theName;
            theName = this.getName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "name", theName), currentHashCode, theName);
        }
        {
            String theSurname;
            theSurname = this.getSurname();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "surname", theSurname), currentHashCode, theSurname);
        }
        {
            String thePesel;
            thePesel = this.getPesel();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "pesel", thePesel), currentHashCode, thePesel);
        }
        {
            CaCountryCode theDocumentCountry;
            theDocumentCountry = this.getDocumentCountry();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "documentCountry", theDocumentCountry), currentHashCode, theDocumentCountry);
        }
        {
            CaDocumentType theDocumentType;
            theDocumentType = this.getDocumentType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "documentType", theDocumentType), currentHashCode, theDocumentType);
        }
        {
            String theDocumentNumber;
            theDocumentNumber = this.getDocumentNumber();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "documentNumber", theDocumentNumber), currentHashCode, theDocumentNumber);
        }
        {
            String theCompanyName;
            theCompanyName = this.getCompanyName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "companyName", theCompanyName), currentHashCode, theCompanyName);
        }
        {
            BigInteger theNip;
            theNip = this.getNip();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nip", theNip), currentHashCode, theNip);
        }
        {
            List<String> thePhone;
            thePhone = (((this.phone!= null)&&(!this.phone.isEmpty()))?this.getPhone():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "phone", thePhone), currentHashCode, thePhone);
        }
        {
            List<String> theEmail;
            theEmail = (((this.email!= null)&&(!this.email.isEmpty()))?this.getEmail():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "email", theEmail), currentHashCode, theEmail);
        }
        {
            List<CaAddress> theAddress;
            theAddress = (((this.address!= null)&&(!this.address.isEmpty()))?this.getAddress():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "address", theAddress), currentHashCode, theAddress);
        }
        {
            List<CaAccount> theAccount;
            theAccount = (((this.account!= null)&&(!this.account.isEmpty()))?this.getAccount():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "account", theAccount), currentHashCode, theAccount);
        }
        {
            CaCustomerDataType theType;
            theType = this.getType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "type", theType), currentHashCode, theType);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
