//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.14 at 03:39:28 PM CET 
//


package pl.edu.wit.jpa.dao.companyB.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for customers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="customer" type="{firmaB}customer" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customers", propOrder = {
    "customer"
})
@Entity(name = "CbCustomers")
@Table(name = "CBCUSTOMERS")
@Inheritance(strategy = InheritanceType.JOINED)
public class CbCustomers
    implements Serializable, Equals, HashCode
{

    @XmlElement(required = true)
    protected List<pl.edu.wit.jpa.dao.companyB.model.CbCustomer> customer;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the customer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link pl.edu.wit.jpa.dao.companyB.model.CbCustomer }
     * 
     * 
     */
    @OneToMany(targetEntity = pl.edu.wit.jpa.dao.companyB.model.CbCustomer.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "CUSTOMER_CBCUSTOMERS_HJID")
    public List<pl.edu.wit.jpa.dao.companyB.model.CbCustomer> getCustomer() {
        if (customer == null) {
            customer = new ArrayList<pl.edu.wit.jpa.dao.companyB.model.CbCustomer>();
        }
        return this.customer;
    }

    /**
     * 
     * 
     */
    public void setCustomer(List<pl.edu.wit.jpa.dao.companyB.model.CbCustomer> customer) {
        this.customer = customer;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof CbCustomers)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final CbCustomers that = ((CbCustomers) object);
        {
            List<pl.edu.wit.jpa.dao.companyB.model.CbCustomer> lhsCustomer;
            lhsCustomer = (((this.customer!= null)&&(!this.customer.isEmpty()))?this.getCustomer():null);
            List<pl.edu.wit.jpa.dao.companyB.model.CbCustomer> rhsCustomer;
            rhsCustomer = (((that.customer!= null)&&(!that.customer.isEmpty()))?that.getCustomer():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "customer", lhsCustomer), LocatorUtils.property(thatLocator, "customer", rhsCustomer), lhsCustomer, rhsCustomer)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            List<CbCustomer> theCustomer;
            theCustomer = (((this.customer!= null)&&(!this.customer.isEmpty()))?this.getCustomer():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "customer", theCustomer), currentHashCode, theCustomer);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
